### ISSUE TITLE
Can you share the checkpoints? How long should the model be trained?

### ISSUE THREAD

**Issue by xinzwang** [yudadabing/Dual-Stream-Transformer-for-Hyperspectral-Image-Restoration#2]
Can you share the checkpoints of CAVE and Harvard dataset with scale factor 4, 8? 

How long should the model be trained? We trained the model for 24 hours on Harvard datasets with scale factor 4. But it did not reach the effect in the paper.

**Comment by GuochaoCS** [comment]
I have also encountered this issue. I trained the model for 30 epochs on the CAVE dataset with a scale factor of 4. However, the final result did not match the performance reported in the paper, achieving a PSNR of only 33.2. I'm concerned that I might be missing some crucial settings. Could you please provide more details about your code and the trained model?

**Comment by yudadabing** [comment]
> Can you share the checkpoints of CAVE and Harvard dataset with scale factor 4, 8?
> 
> How long should the model be trained? We trained the model for 24 hours on Harvard datasets with scale factor 4. But it did not reach the effect in the paper.

**Comment by yudadabing** [comment]
你好，给你带来了困扰，在训练的时候是需要将数据增强打开的，然后我近期会将最新的checkpoint上传的。

<<
train_mslabel_set = loadingData(image_dir=args.train_dir_mslabel, augment=**True**, total_num=args.data_train_num)

**Comment by yudadabing** [comment]
> Can you share the checkpoints of CAVE and Harvard dataset with scale factor 4, 8?
> 
> How long should the model be trained? We trained the model for 24 hours on Harvard datasets with scale factor 4. But it did not reach the effect in the paper.

不好意思，回复晚了，harvard 数据集在训练的时候是需要打开数据增强的，然后整个训练是很慢的，我这边A100是需要训练两周的，Epoch 会选择30, 近期我会逐步将checkpoint 上传的，

**Comment by yudadabing** [comment]
CAVE (x4): https://drive.google.com/file/d/1YhQI7fi5otiD8ZpFwtcUfpQg1L0acwOg/view?usp=share_link

**Comment by yudadabing** [comment]
CAVE (x4): https://drive.google.com/file/d/1YhQI7fi5otiD8ZpFwtcUfpQg1L0acwOg/view?usp=share_link

**Comment by xinzwang** [comment]
非常感谢您的回复和共享。如方便，也请提供Harvard数据的checkpoint，再次感谢
